wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1679780305.883415
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.15
      5: 0.13.9
      8:
      - 1
      - 4
      - 5
architecture:
  desc: null
  value: resnet18
batch_size:
  desc: null
  value: 128
classes:
  desc: null
  value: Index(['rana_sierrae', 'negative'], dtype='object')
comment:
  desc: null
  value: 'Description: training resnet18 on A & E classes and excluding unknown class
    X'
cuda_device_count:
  desc: null
  value: 0
epochs:
  desc: null
  value: 20
l2_regularization:
  desc: null
  value: 0.0005
learning_rate:
  desc: null
  value: 0.002
lr_cooling_factor:
  desc: null
  value: 0.7
lr_update_interval:
  desc: null
  value: 10
model_save_path:
  desc: null
  value: /Users/SML161/ecco12_ramu/rana-sierrae-cnn/resources
mps_available:
  desc: null
  value: true
num_workers:
  desc: null
  value: 12
opensoundscape_version:
  desc: null
  value: 0.8.0
optimizer_cls:
  desc: null
  value: torch.optim.sgd.SGD
sample_duration:
  desc: null
  value: 2.0
sample_shape:
  desc: null
  value: n/a
single_target:
  desc: null
  value: true
